version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    command: nodemon --inspect=0.0.0.0:9229 --watch . index.js
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '9229:9229'